// DEPR (Departamento de Educación de Puerto Rico) alignment.
//
// Grade expectations come from the official DEPR "Estándares de Contenido y
// Expectativas de Grado" (parsed in Genial Skills Maestro); Athenas lessons
// point at sub-indicators of those expectations (3.N.1.2 → expectation 3.N.1).
// Both files are generated by scripts/build-depr-data.mjs.
import standards from './depr-standards.json' with { type: 'json' }
import lessonData from './lesson-standards.json' with { type: 'json' }

const PREFIX = { math: 'mat', spanish: 'esp', english: 'ing', science: 'cie', social: 'est' }

/** "3.N.1.2" → "3.N.1" (grade . domain . expectation) */
export function expectationCode(code) {
  return String(code).split('.').slice(0, 3).join('.')
}

/** Top-level DEPR expectation codes a lesson addresses, limited to one grade. */
export function lessonExpectations(lessonId, level) {
  const codes = lessonData.lessons[String(lessonId)] || []
  const grade = level === 'k' ? 'K' : String(level)
  return [...new Set(codes.map(expectationCode))].filter(c => c.split('.')[0].toUpperCase() === grade.toUpperCase())
}

function domainName(prefix, domain) {
  const names = lessonData.domains[prefix] || {}
  return names[domain] || names[Object.keys(names).find(k => k.replace(/\d+$/, '') === domain)] || domain
}

/**
 * The grade's expectations for a subject, grouped by domain, ready to ship to
 * the browser (the client computes planned / completed coverage from them).
 */
export function gradeExpectations(subjectKey, level) {
  const list = standards[`${PREFIX[subjectKey]}-${level}`]
  if (!list?.length) return null
  const domains = {}
  for (const e of list) domains[e.domain] ??= domainName(PREFIX[subjectKey], e.domain)
  return {
    source: 'DEPR — Estándares de Contenido y Expectativas de Grado (2022)',
    domains,
    expectations: list.map(e => ({ code: e.code, domain: e.domain, text: e.text })),
  }
}
